rotabanner:
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0
  logger:
    level: 20     # INFO level, see https://docs.python.org/2/library/logging.html#levels
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  tornado:
    host: 127.0.0.1
    port: 9180
    debug: !!bool false
    proc_num: 2   # number of tornado workers, ignored in case of debug. 0 implies num of CPU cores.
    base_uri: http://lab.ovg.me/parallels_rotabanner